#!/usr/bin/env python3
import _bootstrap  # noqa: F401
import sys
from datetime import datetime
from workspace_paths import STONEBRIDGE_OPS

BASE = STONEBRIDGE_OPS / "Compliance_Research"
RAW_DIR = BASE / "State_Markdown_Raw"
OUTPUT_DIR = BASE / "State_Reports"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

def generate_report(state):
    raw_file = RAW_DIR / f"{state}_Regulatory_Compliance_Raw.md"
    
    if not raw_file.exists():
        print(f"Error: No raw data found for {state}")
        print(f"Expected file: {raw_file}")
        return

    content = raw_file.read_text()

    # Create a clean report
    report = f"""# {state} - Regulatory Compliance Report

**Generated:** {datetime.now().strftime('%B %d, %Y')}

---

{content}

---

*This report was generated by the Compliance Report Pipeline.*
"""

    output_file = OUTPUT_DIR / f"{state}_Compliance_Report.md"
    output_file.write_text(report)

    print(f"✅ Report created: {output_file}")
    print(f"   You can convert it to PDF using: pandoc {output_file} -o {state}_Compliance_Report.pdf --pdf-engine=weasyprint")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: compliance_report.py <StateName>")
        print("Example: compliance_report.py Pennsylvania")
        sys.exit(1)

    state = sys.argv[1]
    generate_report(state)