#!/usr/bin/env python3
"""Generate 200 DAVID JSONL training pairs for five languages."""
import json
import sys

PAIRS = []

def add(instruction, output):
    PAIRS.append({"instruction": instruction, "input": "", "output": output})

# ========== OLD NORSE (40) ==========
ON = [
("What phonological mistakes does AI audio typically make when generating Old Norse speech?",
 "**Old Norse — common AI audio errors:**\n\nSwapping þ and ð interchangeably (voicing is positional); pronouncing ø/ǫ as English [o]; using English alveolar /r/ instead of palatal ʀ; collapsing West Norse diphthongs to East Norse monophthongs; aspirating voiceless stops; dropping geminate consonants; modern Scandinavian vowel qualities on umlauted forms; flat pacing without Eddic alliterative stress lifts."),
("Generate Grok Imagine audio guidance for producing Old Norse speech in a documentary.",
 "**Old Norse — Grok Imagine audio guidance:**\n\nCommit to: front rounded ø/ǫ; palatal ʀ; þ=[θ] after voiceless, ð=[ð] intervocalic; sustained long vowels/macrons; West Norse diphthongs. Approximate: hl- clusters with voiceless lateral; no stop aspiration. Avoid: modern Icelandic defaults without labeling; silent letters (none exist). Flag: West vs East Norse — label variant on screen.\n\n**Confidence:** high\n**Label as:** Scholarly West Norse reconstruction"),
("What are the distinctive phonological features of Old Norse?",
 "**Old Norse — distinctive features:**\n\nPositional þ/ð voicing; palatal ʀ; front rounded ø/ǫ; phonemic vowel length; umlaut and breaking; gemination; no silent letters; PGmc root-initial stress.\n\n**Vowels:** /a e i o u y ø/ with length; diphthongs ei, au, ey in West Norse\n**Consonants:** þ ð; ʀ; hl/hn/hr clusters; West Norse assimilation mp>pp"),
("What is a memorable pronunciation feature of Old Norse for a language tutoring series?",
 "Palatal ʀ — a rhotic unlike English /r/ or rolled Spanish r; runic and manuscript evidence point to a distinct articulation absent from modern English."),
("What is a surprising or counterintuitive fact about Old Norse for a tutoring series?",
 "There are no silent letters in any period — Younger Futhark dropped vowel signs but sounds were still pronounced; Latin-alphabet spelling is phonetic."),
("What is the hook for a tutoring episode on Old Norse?",
 "Völuspá opens with alliterative power — Hljóðs bið ek allar — and the meter itself teaches which consonants alliterate and which stresses lift."),
("What are the key pronunciation notes for an Old Norse tutoring series?",
 "**Old Norse — pronunciation tutoring notes:**\n\n- þ/ð by position, not spelling\n- ø is front-rounded, not English o\n- Hold long vowels distinctly\n- West Norse diphthongs vs East monophthongization\n- Alliterative lifts on stressed syllables"),
("What professional resources should DAVID use for Old Norse translation work?",
 "**Old Norse — professional resources:**\n\n- Gordon, Introduction to Old Norse\n- Cleasby-Vigfusson dictionary\n- Jackson Crawford reconstructions\n- Codex Regius facsimiles\n- First Grammatical Treatise"),
("What corpus should DAVID prioritize for Old Norse attestation work?",
 "**Old Norse — priority corpus:**\n\n- Codex Regius (GKS 2365 4to): Poetic Edda\n- Snorri Sturluson, Prose Edda\n- Younger Futhark runic inscriptions\n- Heimskringla\n- First Grammatical Treatise"),
("Produce a DAVID corpus entry for this Old Norse text.",
 "**Language:** Old Norse\n**Title:** Völuspá — opening line, st. 1\n**Original:** Hljóðs bið ek allar\n**Translation:** Hearing I ask from all…\n**Source:** Poetic Edda, Völuspá st. 1, Codex Regius\n**Date:** c. 1270 CE (manuscript)\n**Confidence:** [attested]\n**Notes:** DAVID Post 4 hook; IPA is West Norse reconstruction."),
("Situate this Old Norse text in its historical and linguistic context.",
 "**Text:** Völuspá st. 1 — Hljóðs bið ek allar\n**Language:** Old Norse (West Norse) | **Date:** manuscript c. 1270 CE | **Type:** eddic verse\n\n**Source:** Codex Regius, Poetic Edda\n\n**Context:** Seeress summons holy beings; alliterative meter on hl- and vowel lifts."),
("How should DAVID handle Old Norse dialect variation in audio production?",
 "**Old Norse — dialect labeling:**\n\nDefault West Norse for Eddic texts. East Norse monophthongizes ei>ē, au>ø̄ from 10th c. — tag on screen. Runic-period forms more conservative. Never mix West and East vowels in one line without variant label."),
("What IPA should DAVID use for Old Norse Völuspá line 1?",
 "**Text:** Hljóðs bið ek allar, helgar kindir\n**IPA:** /ˈhljoːðs bið ek ˈallar ˈhelɣar ˈkindir/\n**Model:** West Norse — Gordon/Crawford\n**Confidence:** [reconstructed] high"),
("What AI lip-sync risks exist for Old Norse video production?",
 "**Old Norse — lip-sync risks:**\n\nFront rounded ø requires visible lip rounding; hl- clusters need lateral onset not English w; geminate holds need extended viseme duration; þ/ð confusion yields wrong fricative mouth shape."),
("How does DAVID translate Old Norse eddic verse for documentary subtitles?",
 "**Old Norse — translation methodology:**\n\nPreserve alliterative word order where English allows; gloss kennings in second subtitle line; tag [interpretation]; cite stanza; keep Óðinn not Odin in on-screen original unless modernized form labeled."),
("What runic vs manuscript evidence matters for Old Norse pronunciation?",
 "Younger Futhark omits vowel length in script but speech retained it; runic inscriptions show conservative pre-umlaut forms; Icelandic Latin manuscripts are DAVID's phonology anchor."),
("What stress pattern should audio producers follow for Old Norse Eddic poetry?",
 "PGmc root-initial primary stress; secondary stress on compound first element; four stresses per long line with alliterative lifts — heroic pacing, not conversational Scandinavian rhythm."),
("What is Old Norse umlaut and why does it matter for pronunciation?",
 "Umlaut shifts vowels when /i/ or /j/ followed in next syllable (*galiz > gǫlir); produces ǫ and distinct e/ø — AI trained on modern Scandinavian misses these historical vowels."),
("How should producers pronounce Old Norse hl- clusters?",
 "Voiceless lateral onset [hl] — not bl or fl; Hljóðs begins with breathy lateral friction per Gordon IPA and Crawford reference audio."),
("What West vs East Norse split should tutors explain?",
 "West Norse preserves diphthongs ei, au, ey. East Norse monophthongizes from 10th c. Modern Swedish/Danish = East; Icelandic = West — explains divergence students already hear."),
("What gemination rules affect Old Norse audio timing?",
 "Phonemic geminates (pp, tt, kk) from assimilation — hold roughly 2× plain length; mp>pp in West Norse affects compound syllable timing."),
("What is the DAVID confidence tag for Old Norse pronunciation?",
 "Revival tier: high. þ/ð rules well-attested; vowel length and ʀ [reconstructed] with strong consensus. Label: Scholarly West Norse reconstruction."),
("What common subtitle error should Old Norse producers avoid?",
 "Glossing Hljóðs as modern 'loud' without archaic 'hearing/listening' range — corpus-first: 'hearing I ask' per Gordon."),
("How does Old Norse breaking differ from Old English breaking?",
 "Both Germanic, but Old Norse breaking yields au/ei tied to West Norse; Old English yields ea/eo/io — do not conflate outputs despite shared trigger."),
("What manuscript is the gold standard for Old Norse literary pronunciation?",
 "Codex Regius (GKS 2365 4to) for Poetic Edda — with First Grammatical Treatise for contemporary phonological description."),
("What AI training bias causes Old Norse mispronunciation?",
 "Models overfit modern Icelandic (pre-aspiration, later shifts) and apply anachronistically to 9th–11th century Old Norse."),
("How should DAVID mark uncertainty in Old Norse revival drafts?",
 "Tag [attested] for manuscript forms; [reconstructed] for IPA; [hypothesis] for East Norse on West Norse texts; never present IPA as native certainty."),
("What alliterative pattern appears in Hljóðs bið ek allar?",
 "Initial hl- alliterates with helgar in line 2; punch stress on Hljóðs and allar for meter authenticity."),
("What Old Norse consonant has no English equivalent?",
 "Palatal ʀ — neither English approximant nor trill; ø/ǫ front rounded vowels lack English monophthong equivalents."),
("How do Younger Futhark limitations affect pronunciation teaching?",
 "16-sign rune set compresses vowel notation — script ambiguity ≠ sound merger; vowels were still distinct in speech."),
("What saga prose differs from eddic verse for audio pacing?",
 "Prose Edda uses looser rhythm than eddic meter — do not apply heroic line pacing to Snorri's explanatory prose."),
("What Old Norse vowel length evidence exists?",
 "Manuscript doubling, meter, and comparative Scandinavian evidence support phonemic length — AI often shortens ó without duration cue."),
("How should translators handle Old Norse kennings in corpus entries?",
 "Expand kenning in translation; keep compound in transliteration; tag [kenning]; cite Cleasby-Vigfusson expansion."),
("What is the Old Norse revival tier and what does it imply for production?",
 "Revival tier: high — spoken revival allowed with [reconstructed] tags; never invent unattested forms for drama."),
("What near-death pronunciation pitfall affects Old Norse þ?",
 "Voiceless [θ] degraded to [t] in some dialects — AI outputs [t] for þ; enforce fricative per grammatical treatise tradition."),
("How does DAVID cross-link Old Norse corpus to History content?",
 "Saga figures (Harald Fairhair, Snorri) pull period/region from Heimskringla; phonology can anchor to dated runestone for contemporary snapshot."),
("What Old Norse audio reference clips should Grok Imagine use?",
 "Jackson Crawford readings; Gordon IPA; avoid modern Norwegian/Swedish unless labeled East Norse variant."),
("What forensic step precedes Old Norse pronunciation rendering?",
 "Corpus before grammar: verify in Codex Regius or inscription, then apply West Norse model — never reverse from English cognate."),
("What tutoring exercise teaches Old Norse þ/ð voicing?",
 "Drill þat (voiceless initial) vs bið (voiced intervocalic); environment rule before spelling — thorn and eth are positional allographs."),
("What production note applies to Old Norse compound stress?",
 "Secondary stress on first compound root — affects subtitle breath groups in Eddic delivery."),
]
for i, o in ON:
    add(i, o)

# ========== OLD ENGLISH (40) ==========
OE = [
("What phonological mistakes does AI audio typically make when generating Old English speech?",
 "**Old English — common AI audio errors:**\n\nPronouncing hw as plain /w/; reducing æ to modern ash diphthong; swapping þ/ð regardless of environment; collapsing breaking diphthongs ea/eo/io; missing intervocalic ɣ; applying Modern English schwa reduction; palatalizing c/g before back vowels; treating Hwæt as modern 'what' intonation."),
("Generate Grok Imagine audio guidance for producing Old English speech in a documentary.",
 "**Old English — Grok Imagine audio guidance:**\n\nCommit to: æ=[æ] as in 'cat'; hw/ʍ distinct from w; þ/ð by environment; breaking diphthongs sustained; palatal c/g → tʃ/dʒ before front vowels; intervocalic ɣ. Approximate: long vowels held 2×; strong alliterative stresses. Avoid: Modern English vowel reduction; pronouncing Hwæt as interrogative 'what'. Flag: Late West Saxon default.\n\n**Confidence:** high\n**Label as:** Scholarly Late West Saxon reconstruction"),
("What are the distinctive phonological features of Old English?",
 "**Old English — distinctive features:**\n\nhw/ʍ voiceless labial-velar; positional þ/ð; breaking diphthongs ea/eo/io; palatalized c/g; intervocalic ɣ; phonemic vowel length; PGmc stress with alliterative meter.\n\n**Vowels:** æ, ā, ēa, ēo with length contrast\n**Consonants:** þ ð; ʍ; ɣ; geminates in West Saxon literary forms"),
("What is a memorable pronunciation feature of Old English for a language tutoring series?",
 "Hwæt! — dramatic summons 'Listen!' or 'So!' with voiceless ʍ onset, not modern interrogative 'what' — the opening of Beowulf is a performance cue."),
("What is a surprising or counterintuitive fact about Old English for a tutoring series?",
 "Alliterative meter works like ancient rap battles — four stresses per line, lifts drive word choice; poets chose synonyms to satisfy sound pattern."),
("What is the hook for a tutoring episode on Old English?",
 "Beowulf opens Hwæt! We Gardena in geardagum — hear how alien yet ancestral English sounds when æ, ʍ, and ɣ are restored."),
("What are the key pronunciation notes for an Old English tutoring series?",
 "**Old English — pronunciation tutoring notes:**\n\n- æ = [æ] not diphthong\n- hw = [ʍ] not [w]\n- þ voiceless initially, ð voiced intervocalically\n- Sustain ea/eo breaking diphthongs\n- No schwa reduction in unstressed syllables"),
("What professional resources should DAVID use for Old English translation work?",
 "**Old English — professional resources:**\n\n- Mitchell & Robinson, Guide to Old English\n- Bosworth-Toller dictionary\n- Campbell 1959 historical grammar\n- Hogg 1992 phonology\n- Cotton Vitellius A.xv facsimile (Beowulf)"),
("What corpus should DAVID prioritize for Old English attestation work?",
 "**Old English — priority corpus:**\n\n- Beowulf (Cotton Vitellius A.xv)\n- Anglo-Saxon Chronicle\n- Cædmon's Hymn (Northumbrian and West Saxon copies)\n- Exeter Book poetry\n- Laws of Æthelberht / Alfred"),
("Produce a DAVID corpus entry for this Old English text.",
 "**Language:** Old English\n**Title:** Beowulf — opening line\n**Original:** Hwæt! We Gardena in geardagum\n**Translation:** Listen! We have heard of the glory of the Spear-Danes in days of old\n**Source:** Beowulf l. 1, Cotton Vitellius A.xv\n**Date:** c. 1000 CE (manuscript)\n**Confidence:** [attested]\n**Notes:** Late West Saxon pronunciation baseline."),
("Situate this Old English text in its historical and linguistic context.",
 "**Text:** Beowulf l. 1 — Hwæt! We Gardena in geardagum\n**Language:** Old English (Late West Saxon) | **Date:** c. 1000 CE | **Type:** epic verse\n\n**Source:** British Library Cotton Vitellius A.xv\n\n**Context:** Scribe summons audience to Danish heroic past; alliterative w/g lifts across line boundary."),
("How should DAVID handle Old English dialect variation in audio production?",
 "**Old English — dialect labeling:**\n\nDefault Late West Saxon literary (Beowulf). Northumbrian retains /io/ with less breaking. Early West Saxon heavier breaking. Tag variant on screen when using Anglian forms on West Saxon text."),
("What IPA should DAVID use for Beowulf line 1?",
 "**Text:** Hwæt! We Gardena in geardagum\n**IPA:** /ˈhwæt weː ˈɡɑːrˌde.na in ˈjæɑrˌdɑ.ɣum/\n**Model:** Late West Saxon — Mitchell & Robinson\n**Confidence:** [reconstructed] high"),
("What AI lip-sync risks exist for Old English video production?",
 "**Old English — lip-sync risks:**\n\nʍ requires lip rounding distinct from w; intervocalic ɣ needs open velar fricative not g stop; breaking diphthongs need extended vowel viseme transitions; strong stress lifts cause subtitle-audio misalignment if timed to weak syllables."),
("How does DAVID translate Old English poetry for documentary subtitles?",
 "**Old English — translation methodology:**\n\nPreserve alliterative stress alignment in English gloss where possible; note compound semantics (Gardena = Spear-Danes); tag archaisms; cite line number; separate meter-sensitive wording from prose paraphrase layer."),
("What breaking vs smoothing should Old English tutors teach?",
 "Breaking: PGmc vowels split to diphthongs before certain consonants (eald, beorht). Smoothing: later reduction within diphthong — explain why modern English lost the alien vowel clusters."),
("What stress pattern should audio producers follow for Old English verse?",
 "PGmc root-initial primary; unstressed prefixes (ġe-, be-); compounds stress first root; four alliterative stresses per line — heroic deliberate pacing."),
("What is Old English æ and why do AI models fail on it?",
 "Monophthong [æ] as in 'cat' — not modern English ash glide; models trained on contemporary English diphthongize æ in hwæt, fæder."),
("How should producers pronounce Old English intervocalic ɣ?",
 "Voiced velar fricative [ɣ] between vowels (geardagum) — not hard [g]; disappears in Middle English — students hear direct ancestor of silent gh pattern."),
("What West Saxon vs Northumbrian split should tutors explain?",
 "West Saxon literary standard dominates classroom; Northumbrian Cædmon's Hymn shows different vowel developments — same language, different phonological snapshot."),
("What palatalization rules affect Old English audio?",
 "c/g palatalize to [tʃ]/[dʒ] before front vowels (cild, giefan) — AI often keeps hard stops anachronistically."),
("What is the DAVID confidence tag for Old English pronunciation?",
 "Revival tier: medium-high. Consonants and stress well-attested via meter; short diphthong realization partly disputed. Label: Scholarly Late West Saxon reconstruction."),
("What common subtitle error should Old English producers avoid?",
 "Rendering Hwæt as 'What!' interrogative — corpus gloss: summons 'Listen!' or 'Lo!' per Mitchell & Robinson."),
("How does Old English hw differ from Old Norse hl pedagogically?",
 "Both are voiceless onset clusters but hw is labial-velar [ʍ] (English which-type) while Old Norse hl is lateral — do not teach same mouth shape."),
("What manuscript is the gold standard for Old English epic pronunciation?",
 "Cotton Vitellius A.xv (British Library) for Beowulf — Late West Saxon literary norm despite Danish subject matter."),
("What AI training bias causes Old English mispronunciation?",
 "Models default to Shakespearean or KJV cadence — wrong era — and schwa-reduce unstressed syllables Old English pronounced fully."),
("How should DAVID mark uncertainty in Old English revival drafts?",
 "Tag [attested] for manuscript spelling; [reconstructed] for IPA; [hypothesis] for Northumbrian vowel on West Saxon line; meter confirms stress even when vowel quality debated."),
("What alliterative pattern appears in Beowulf line 1?",
 "Hwæt sets lift; We/Gardena/geardagum carry w/g alliteration across half-line — producers punch We and Gardena stresses."),
("What Old English consonant has no Modern English equivalent?",
 "Voiceless labial-velar ʍ (hw) — which/what distinction lost in most modern English; intervocalic ɣ also absent."),
("How does i-mutation appear in Old English tutoring?",
 "Front vowel mutation from following /i/ or /j/ (mus > mys 'mice') — connects pronunciation to plural morphology students see in texts."),
("What prose differs from verse for Old English audio pacing?",
 "Anglo-Saxon Chronicle prose lacks strict alliterative meter — use narrative pacing for annals, heroic lifts only for poetry."),
("What Old English vowel length evidence exists?",
 "Alliteration and rhyme patterns plus spelling distinctions (macron letters in editions) — hold long ā in Gardena distinctly."),
("How should translators handle Old English compounds in corpus entries?",
 "Split compound gloss (gar = spear, Dena = Danes); keep compound in original; tag [compound] with morpheme boundaries."),
("What is the Old English revival tier and what does it imply for production?",
 "Revival tier: medium — strong literary corpus but dialect variation; spoken revival requires [reconstructed] tags and West Saxon label."),
("What near-death pronunciation pitfall affects Old English ð?",
 "Final ð often voiceless [θ] — AI voices all eth as [ð]; follow environment rule for authentic fricative distribution."),
("How does DAVID cross-link Old English corpus to History content?",
 "Alfredian translations, Bede's Ecclesiastical History excerpts, and Chronicle annals tie to dated events — pronunciation snapshot c. 9th–10th c. West Saxon court."),
("What Old English audio reference clips should Grok Imagine use?",
 "Mitchell & Robinson OCW readings; British Library Beowulf recitations; avoid generic 'medieval' fantasy accent."),
("What forensic step precedes Old English pronunciation rendering?",
 "Verify form in manuscript edition (Krapp-Dobbie, Fulk) before applying phonology — scribal normalization can hide dialect spelling."),
("What tutoring exercise teaches Old English þ/ð voicing?",
 "Compare þæt (initial voiceless) with fæder (medial voiced ð) — same allographs as Old Norse but different vocabulary set."),
("What production note applies to Old English caesura breathing?",
 "Half-line pause in long lines — audio producers insert breath at metrical caesura for authentic recitation cadence."),
]
for i, o in OE:
    add(i, o)

# ========== SUMERIAN (40) ==========
SU = [
("What phonological mistakes does AI audio typically make when generating Sumerian speech?",
 "**Sumerian — common AI audio errors:**\n\nPronouncing logograms as English words; false confidence on ĝ (random g or ng); treating r as English r; ignoring compound boundaries; applying Akkadian emphatics to Sumerian; inventing stress patterns; reading subscript digits aloud; using modern Arabic/Hebrew gutturals by default; flat pacing across morpheme breaks."),
("Generate Grok Imagine audio guidance for producing Sumerian speech in a documentary.",
 "**Sumerian — Grok Imagine audio guidance:**\n\nCommit to: slow compound-internal pacing; separate ergative endings; ĝ as [ŋ] or [ɡ] (label disputed). Approximate: r as light tap; ḫ as velar/uvular fricative; a e i u vowels without English diphthongs. Avoid: false precision; reading every cuneiform sign as syllable without phonotactic check. Flag: all output [hypothesis].\n\n**Confidence:** low\n**Label as:** Scholarly hypothesis — lowest confidence in DAVID registry"),
("What are the distinctive phonological features of Sumerian?",
 "**Sumerian — distinctive features:**\n\nLanguage isolate; ergative-agglutinative morphology; logographic + phonetic writing; vowel harmony uncertain; no certain stress; Emesal vs Emegir dialect contrast via Akkadian lens.\n\n**Consonants:** ĝ ḫ r disputed; limited attestation of clusters\n**Vowels:** a e i u; length and harmony [hypothesis]"),
("What is a memorable pronunciation feature of Sumerian for a language tutoring series?",
 "World's oldest attested written language (c. 3200 BCE) — yet we reconstruct its sounds almost entirely through Akkadian scribal ears, not Sumerian native speakers."),
("What is a surprising or counterintuitive fact about Sumerian for a tutoring series?",
 "The language outlived everyday use — Babylonian scribes copied Sumerian hymns for centuries after nobody spoke it at home, like Latin in medieval Europe."),
("What is the hook for a tutoring episode on Sumerian?",
 "ud re-a ud su-ra re-a — 'In those days, in those distant days' — opening formula older than the pyramids' written tradition."),
("What are the key pronunciation notes for a Sumerian tutoring series?",
 "**Sumerian — pronunciation tutoring notes:**\n\n- All audio tagged [hypothesis]\n- ĝ disputed: velar nasal or stop\n- Slow pacing across compounds\n- Ergative -e enunciated separately\n- Do not assert stress confidently"),
("What professional resources should DAVID use for Sumerian translation work?",
 "**Sumerian — professional resources:**\n\n- Jagersma, Descriptive Grammar of Sumerian\n- Thomsen, The Sumerian Language\n- ETCSL (Oxford)\n- CDLI corpus\n- ePSD2 sign list"),
("What corpus should DAVID prioritize for Sumerian attestation work?",
 "**Sumerian — priority corpus:**\n\n- ETCSL literary texts (5.x series)\n- Instructions of Shuruppak (5.6.1)\n- Gudea cylinders\n- Lugalbanda and Enmerkar cycles\n- Bilingual Sumerian-Akkadian tablets (CDLI)"),
("Produce a DAVID corpus entry for this Sumerian text.",
 "**Language:** Sumerian\n**Title:** Instructions of Shuruppak — opening formula\n**Original:** ud re-a ud su-ra re-a\n**Translation:** In those days, in those distant days…\n**Source:** ETCSL 5.6.1, line 1\n**Date:** c. 2600 BCE tradition\n**Confidence:** [attested]\n**Notes:** DAVID Post 2 hook; spoken vowels [reconstructed]."),
("Situate this Sumerian text in its historical and linguistic context.",
 "**Text:** Instructions of Shuruppak opening\n**Language:** Sumerian (Emegir) | **Date:** Old Babylonian copies of older tradition | **Type:** wisdom literature\n\n**Source:** ETCSL 5.6.1\n\n**Context:** Flood-survival wisdom attributed to Shuruppak; formulaic temporal opener for mythic past."),
("How should DAVID handle Sumerian dialect variation in audio production?",
 "**Sumerian — dialect labeling:**\n\nEmegir (standard literary) vs Emesal (women's/liturgical dialect) — Emesal known mainly through Akkadian transcriptions; tag [Emesal] if using liturgical forms; default Emegir for ETCSL literary texts."),
("What IPA should DAVID use for Sumerian en-lil2 lugal kalam-ma?",
 "**Text:** en-lil2 lugal kalam-ma\n**Romanization:** enlil lugal kalam-ma\n**IPA:** /en.lil lu.ɡal ka.lam.ma/ (approximate)\n**Model:** Jagersma/Thomsen conventional\n**Confidence:** [hypothesis] low"),
("What AI lip-sync risks exist for Sumerian video production?",
 "**Sumerian — lip-sync risks:**\n\nDisputed ĝ gives unstable velar/nasal viseme; agglutinative chains need morpheme-synced mouth rhythm; low-confidence vowels make lip-sync uncanny if presented as certain."),
("How does DAVID translate Sumerian for documentary subtitles?",
 "**Sumerian — translation methodology:**\n\nLine-by-line ETCSL gloss; preserve ergative case markers in linguistic overlay; tag every vocalization [reconstructed]; never produce faux-native dialogue without revival draft label."),
("What Akkadian borrowing evidence helps Sumerian pronunciation?",
 "Akkadian scribes transcribed Sumerian names and words in syllabic cuneiform — primary window for consonants; vowel qualities inferred with low confidence."),
("What stress pattern should audio producers use for Sumerian?",
 "Unknown — likely final or compound-internal per some scholars; DAVID instructs: do not assert stress confidently; use even pacing with compound breaks."),
("What is Sumerian ĝ and why is it disputed?",
 "Cuneiform distinguishes ĝ from g but phonetic value uncertain — velar nasal [ŋ], voiced stop [ɡ], or palatal; see disputed_phonemes.json; AI must not pick one without on-screen dispute flag."),
("How should producers handle Sumerian logographic spellings?",
 "Read phonetic complements and morpheme boundaries — do not pronounce logogram as English semantic equivalent; forensic parse sign-by-sign."),
("What Emesal dialect hook should tutors use?",
 "Emesal surfaces in women's laments and liturgy — different lexical items preserved via Akkadian commentaries; shows Sumerian was not monolithic."),
("What agglutinative morphology affects Sumerian audio?",
 "Ergative -e, plural -ene, case chains — enunciate suffixes separately; AI often smears endings into stem."),
("What is the DAVID confidence tag for Sumerian pronunciation?",
 "Revival tier: high for grammar attestation; pronunciation confidence: lowest in registry. All audio [hypothesis]; never inflate to medium without bilingual evidence cite."),
("What common subtitle error should Sumerian producers avoid?",
 "Presenting Jagersma romanization as heard-by-native-speakers — always subtitle 'reconstructed pronunciation' disclaimer."),
("How does Sumerian isolation affect pedagogical framing?",
 "No cognate language family — cannot use comparative reconstruction like Indo-European; Akkadian lens is almost sole phonology evidence."),
("What corpus is the gold standard for Sumerian literary pronunciation?",
 "ETCSL curated editions with line numbering — Instructions of Shuruppak 5.6.1 for DAVID canonical opener."),
("What AI training bias causes Sumerian mispronunciation?",
 "Models conflate with Akkadian (Semitic emphatics) or Arabic gutturals — Sumerian is isolate with different phonology; also confuse Sumerian logograms read as Akkadian phonetic values."),
("How should DAVID mark uncertainty in Sumerian revival drafts?",
 "Mandatory [hypothesis] on all spoken output; [attested] only for transliteration; [unknown] for stress and vowel length claims."),
("What tutoring exercise teaches Sumerian ergative case?",
 "Drill lugal-e e mu-un-pad 'the king built the temple' — ergative -e on agent with slow ending enunciation for audio."),
("What Sumerian consonant has no consensus IPA?",
 "ĝ and r both disputed; ḫ inferred from Akkadian borrowing — present multiple scholarly options in tutoring sidebar."),
("How do cuneiform subscripts affect production?",
 "Subscript 2/3 (š4, il2) are sign-index conventions — not pronounced; strip for romanization before IPA pass."),
("What liturgical survival differs from everyday Sumerian for audio?",
 "Post-death liturgical use in Babylon — scribes chanted with learned pronunciation [hypothesis] — slower, more segmented than conversational speech [unknown]."),
("What Sumerian vowel harmony uncertainty means for audio?",
 "Some scholars posit vowel harmony in affixes — DAVID does not enforce in audio without tagging [hypothesis]; use neutral a e i u."),
("How should translators handle Sumerian compounds in corpus entries?",
 "Morpheme gloss per ePSD2; Sumerian compounds often agglutinative — show kalam-ma 'land' as kalam + ma if evidence supports."),
("What is the Sumerian revival tier and what does it imply for production?",
 "Revival tier: high for text; pronunciation: research-grade uncertainty — spoken revival is educational illustration only, never definitive dubbing."),
("What near-death pronunciation pitfall affects Sumerian ḫ?",
 "AI uses English h or Arabic ḥ — infer velar/uvular fricative from Akkadian ḫ correspondence with low confidence tag."),
("How does DAVID cross-link Sumerian corpus to History content?",
 "Gudea of Lagash, Shulgi hymns, Uruk III administrative tablets — tie pronunciation lesson to period (Early Dynastic vs Ur III)."),
("What Sumerian audio reference should Grok Imagine use?",
 "No native recordings exist — use slow Jagersma-style romanization demo with visible [hypothesis] watermark; never mimic Akkadian epic pacing."),
("What forensic step precedes Sumerian pronunciation rendering?",
 "Parse cuneiform to phonetic chain via ETCSL transliteration; check bilingual Akkadian column for consonant clues; then apply lowest-confidence profile."),
("What production note applies to Sumerian compound pacing?",
 "Pause at morpheme boundaries (en-lil2 | lugal | kalam-ma) — helps learners hear agglutination even when phonetics uncertain."),
("What research query should queue after Sumerian pronunciation lesson?",
 "Expand bilingual tablet sample for ĝ and r phoneme narrowing — research_query_generator.py --language sumerian --focus disputed_phonemes."),
]
for i, o in SU:
    add(i, o)

# ========== AKKADIAN (40) ==========
AK = [
("What phonological mistakes does AI audio typically make when generating Akkadian speech?",
 "**Akkadian — common AI audio errors:**\n\nDropping final mimation (-m); collapsing emphatics ṭ/ṣ/q to plain stops; using Modern Hebrew/Arabic emphatic defaults without dialect label; shortening phonemic long vowels; ignoring glottal aleph; pronouncing š as /s/; Neo-Assyrian sibilants on Standard Babylonian literary text; flat pacing without epic parallelism breath groups."),
("Generate Grok Imagine audio guidance for producing Akkadian speech in a documentary.",
 "**Akkadian — Grok Imagine audio guidance:**\n\nCommit to: emphatics ṭ/q/ṣ as throaty or lightly ejective; sustain long vowels; pronounce mimation; glottal aleph [ʔ] where marked; š=[ʃ]. Approximate: penultimate stress in literary forms. Avoid: Modern Hebrew/Arabic emphatic timbre without dialect tag. Flag: Standard Babylonian default for literary/epic.\n\n**Confidence:** medium-high\n**Label as:** Scholarly Standard Babylonian reconstruction"),
("What are the distinctive phonological features of Akkadian?",
 "**Akkadian — distinctive features:**\n\nSemitic emphatics; phonemic vowel length from V/VV signs; mimation on nouns/adjectives; glottal aleph; š distinct from s; dialect split Old Babylonian / Standard Babylonian / Neo-Assyrian.\n\n**Vowels:** a i u e with length contrast\n**Consonants:** ṭ ṣ q emphatics; mimation; ʔ aleph"),
("What is a memorable pronunciation feature of Akkadian for a language tutoring series?",
 "Emphatic consonants ṭ/q/ṣ — throaty or popped articulation distinguishing Akkadian from its Semitic cousins Hebrew and Arabic in reconstruction convention."),
("What is a surprising or counterintuitive fact about Akkadian for a tutoring series?",
 "Akkadian was the lingua franca of the Near East for 2,000+ years — diplomats wrote to Pharaoh in Akkadian cuneiform, not Egyptian."),
("What is the hook for a tutoring episode on Akkadian?",
 "ša nagba imuru — Gilgamesh Tablet I 'He who saw the Deep' — epic opener with š=[ʃ] and long vowels held in parallelism."),
("What are the key pronunciation notes for an Akkadian tutoring series?",
 "**Akkadian — pronunciation tutoring notes:**\n\n- Emphatics throaty/ejective (conventional)\n- Long vowels phonemic — hold duration\n- Mimation -m pronounced on nouns\n- š = [ʃ] as in 'ship'\n- Standard Babylonian for literary corpus"),
("What professional resources should DAVID use for Akkadian translation work?",
 "**Akkadian — professional resources:**\n\n- Huehnergard, Grammar of Akkadian\n- von Soden, Grundriss\n- Chicago Assyrian Dictionary (CAD)\n- ORACC corpus\n- George 2003 Gilgamesh edition"),
("What corpus should DAVID prioritize for Akkadian attestation work?",
 "**Akkadian — priority corpus:**\n\n- Epic of Gilgamesh (Standard Babylonian)\n- Enuma Elish creation epic\n- Amarna letters (diplomatic corpus)\n- Code of Hammurabi\n- ORACC Royal Inscriptions"),
("Produce a DAVID corpus entry for this Akkadian text.",
 "**Language:** Akkadian\n**Title:** Epic of Gilgamesh — SB Tablet I opening\n**Original:** ša nagba imuru\n**Translation:** He who saw the Deep\n**Source:** Gilgamesh SB Tablet I; ORACC\n**Date:** 1st millennium BCE standard recension\n**Confidence:** [attested]\n**Notes:** DAVID Post 5 hook; š=[ʃ]; vowels from Semitic root structure."),
("Situate this Akkadian text in its historical and linguistic context.",
 "**Text:** Gilgamesh SB I — ša nagba imuru\n**Language:** Akkadian (Standard Babylonian) | **Date:** 1st millennium BCE | **Type:** epic incipit\n\n**Source:** ORACC; George 2003\n\n**Context:** Relative clause opening epic biography; nagbu 'flood/deep' ties to wisdom-through-adventure theme."),
("How should DAVID handle Akkadian dialect variation in audio production?",
 "**Akkadian — dialect labeling:**\n\nStandard Babylonian for literary/epic (DAVID default). Old Babylonian: fuller vowels. Neo-Assyrian: later sibilant/emphatic shifts. Tag on screen — do not apply Neo-Assyrian to Gilgamesh SB without justification."),
("What IPA should DAVID use for Enuma Elish opening?",
 "**Text:** enūma eliš lā nabû šamāmu\n**IPA:** /e.nuː.ma e.liʃ laː na.buː ʃa.maː.mu/\n**Model:** Standard Babylonian — Huehnergard\n**Confidence:** [reconstructed] medium-high"),
("What AI lip-sync risks exist for Akkadian video production?",
 "**Akkadian — lip-sync risks:**\n\nEmphatics need visible constriction AI maps to plain stops; long vowels need duration sync; final mimation -m often dropped in TTS lip models trained on languages without case -m."),
("How does DAVID translate Akkadian for documentary subtitles?",
 "**Akkadian — translation methodology:**\n\nFollow George/Huehnergard line glosses; preserve parallelism in couplet structure; tag broken or damaged signs [lacuna]; Semitic root gloss optional in linguistic overlay."),
("What cuneiform sign evidence supports Akkadian vowel length?",
 "V/VV sign contrast in syllabary — phonemic length well supported; producers hold ū in enūma distinctly unlike short u."),
("What stress pattern should audio producers follow for Akkadian epic?",
 "Penultimate or morphologically determined stress; epic parallelism favors deliberate phrasing — breath at couplet boundary."),
("What is Akkadian mimation and why do AI models drop it?",
 "Final -m on nouns/adjectives (shamānu > šamāmu in pausal forms context-dependent) — cuneiform often writes it; TTS trained on languages without mimation omits it."),
("How should producers articulate Akkadian emphatics?",
 "Conventional reconstruction: pharyngealized or lightly ejective ṭ/q/ṣ — not plain t/k/s; label as scholarly convention, debated articulation."),
("What Standard Babylonian vs Neo-Assyrian hook should tutors use?",
 "Same empire tradition, different phonological snapshot — Neo-Assyrian š sometimes shifts; literary Babylonian conservative for classroom epic."),
("What Semitic root structure affects Akkadian tutoring?",
 "Triconsonantal roots (N-G-B 'see' in nagba) — connect pronunciation drills to root consonants surviving vowel melody changes."),
("What is the DAVID confidence tag for Akkadian pronunciation?",
 "Revival tier: high. Consonants and vowel length: medium-high confidence. Emphatic manner: conventional [reconstructed]. Label: Standard Babylonian."),
("What common subtitle error should Akkadian producers avoid?",
 "Translating ša only as 'that' without noting relative 'who/which' function in ša nagba imuru incipit formula."),
("How does Akkadian relate to Biblical Hebrew for pronunciation pedagogy?",
 "Cousin Semitic languages — shared emphatics and glottals but different vowel systems; do not apply Hebrew vocalization to Akkadian cuneiform reading."),
("What corpus is the gold standard for Akkadian epic pronunciation?",
 "George 2003 Standard Babylonian Gilgamesh with ORACC transliteration — DAVID default for ša nagba imuru."),
("What AI training bias causes Akkadian mispronunciation?",
 "Models apply Modern Standard Arabic emphatics and Hebrew biblical cadence — wrong period and dialect; also read cuneiform logograms as Sumerian values."),
("How should DAVID mark uncertainty in Akkadian revival drafts?",
 "Tag [attested] for cuneiform reading; [reconstructed] for emphatic manner and stress; [hypothesis] for Neo-Assyrian variant on SB text."),
("What tutoring exercise teaches Akkadian š vs s?",
 "Contrast šamū 'sky' [ʃ] with sūtu 'sleep' — cuneiform distinguishes signs; AI often collapses to /s/."),
("What Akkadian consonant has no European equivalent?",
 "Emphatic ṣ/ṭ/q set — requires Semitic articulation training; glottal aleph if vowel-initial forms."),
("How do multi-value cuneiform signs affect production?",
 "One sign, multiple syllabic values — context picks reading; forensic step: check ORACC normalization before IPA."),
("What diplomatic corpus differs from epic for Akkadian audio?",
 "Amarna letters: practical Akkadian with Canaanite scribe interference — looser, less poetic pacing than Gilgamesh parallelism."),
("What Akkadian vowel reduction evidence exists?",
 "Later dialects reduce unstressed vowels — Standard Babylonian literary forms retain fuller vowels; do not apply reduction to SB epic without dialect tag."),
("How should translators handle Akkadian broken tablets in corpus entries?",
 "Mark [lacuna] in transliteration; do not reconstruct missing signs for pronunciation demo; lip-sync only attested sequences."),
("What is the Akkadian revival tier and what does it imply for production?",
 "Revival tier: high — 2,000-year corpus; spoken revival viable for epic with [reconstructed] emphatic tag."),
("What near-death pronunciation pitfall affects Akkadian aleph?",
 "AI treats aleph as zero onset — insert glottal stop [ʔ] where sign values and Semitic pattern require."),
("How does DAVID cross-link Akkadian corpus to History content?",
 "Hammurabi, Ashurbanipal's library, Amarna diplomacy — pronunciation lesson can anchor to dated archive (Nineveh vs Old Babylon)."),
("What Akkadian audio reference should Grok Imagine use?",
 "Huehnergard pedagogical recordings; avoid MSA/Quran cadence unless labeled comparative Semitic sidebar."),
("What forensic step precedes Akkadian pronunciation rendering?",
 "Normalize transliteration via ORACC/CAD; confirm dialect (SB vs OA); then map sign vowel length before emphatic pass."),
("What production note applies to Akkadian parallel couplets?",
 "Enuma Elish and Gilgamesh use semantic parallelism — audio breath at couplet end mirrors poetic structure."),
("What research query should queue after Akkadian emphatic lesson?",
 "Compare Neo-Assyrian sibilant reflexes in royal inscriptions vs SB literary conservatism — research_query_generator.py --language akkadian."),
]
for i, o in AK:
    add(i, o)

# ========== MIDDLE EGYPTIAN (40) ==========
ME = [
("What phonological mistakes does AI audio typically make when generating Middle Egyptian speech?",
 "**Middle Egyptian — common AI audio errors:**\n\nPronouncing hieroglyphs as consonant-only strings without vowels; treating ꜥ (ayin) as silent; using English th for ḫ; ignoring ejectives pʼ/tʼ/kʼ; inserting English diphthongs into reconstructed vowels; applying Coptic vowels anachronistically to Middle Egyptian stage; dropping glottal ꜣ; uniform stress like English; no [reconstructed] vowel disclaimer."),
("Generate Grok Imagine audio guidance for producing Middle Egyptian speech in a documentary.",
 "**Middle Egyptian — Grok Imagine audio guidance:**\n\nCommit to: ejectives pʼ/tʼ/kʼ with glottal pop; pharyngeal ꜥ [ʕ]; emphatics heavier than plain; glottal ꜣ [ʔ]. Approximate: epenthetic schwa [ə] in unstressed slots; pure a/i/u without English diphthongs. Avoid: consonant-only recitation; English th for ḫ. Flag: all vowels [reconstructed] on screen.\n\n**Confidence:** medium-low\n**Label as:** Scholarly reconstruction of Middle Egyptian"),
("What are the distinctive phonological features of Middle Egyptian?",
 "**Middle Egyptian — distinctive features:**\n\nConsonantal script — all vowels inserted; ejectives pʼ/tʼ/kʼ; pharyngeal ꜥ and ḥ; emphatic consonants; glottal ꜣ; Afroasiatic alignment with Coptic reflexes.\n\n**Vowels:** all [reconstructed] via Coptic/comparative\n**Consonants:** ꜥ ꜣ ḫ ḥ q emphatics; ejective stops"),
("What is a memorable pronunciation feature of Middle Egyptian for a language tutoring series?",
 "ꜥ (ayin) — a deep throat constriction like Arabic ع — not a vowel, not silent; hieroglyphs hide it between consonants students must learn to hear."),
("What is a surprising or counterintuitive fact about Middle Egyptian for a tutoring series?",
 "Hieroglyphs spell consonants only — every vowel you hear in class is Egyptological insertion tagged [reconstructed], never attested in original script."),
("What is the hook for a tutoring episode on Middle Egyptian?",
 "ꜥnḫ wḏꜣ snb — 'life, prosperity, health' — tomb formula whose three words teach ꜥ, wḏ, and snb consonant skeleton plus reconstructed vowels."),
("What are the key pronunciation notes for a Middle Egyptian tutoring series?",
 "**Middle Egyptian — pronunciation tutoring notes:**\n\n- Vowels always [reconstructed]\n- ꜥ = pharyngeal [ʕ], not silent\n- Ejectives with glottal pop\n- Epenthetic schwa in unstressed slots\n- Tag Coptic-reflex model on screen"),
("What professional resources should DAVID use for Middle Egyptian translation work?",
 "**Middle Egyptian — professional resources:**\n\n- James P. Allen, Middle Egyptian (3rd ed.)\n- Loprieno, Ancient Egyptian Linguistic Introduction\n- Peust, Egyptian Phonology\n- Faulkner dictionary\n- Griffith Institute hieroglyphic corpus"),
("What corpus should DAVID prioritize for Middle Egyptian attestation work?",
 "**Middle Egyptian — priority corpus:**\n\n- Coffin Texts\n- Book of the Dead (Saite recension inherits ME grammar)\n- Sinuhe tale\n- Amarna letters (Egyptian sections)\n- Stelae with ꜥnḫ wḏꜣ snb formula"),
("Produce a DAVID corpus entry for this Middle Egyptian text.",
 "**Language:** Middle Egyptian\n**Title:** Royal blessing formula\n**Original:** ꜥnḫ wḏꜣ snb\n**Translation:** Life, prosperity, health\n**Source:** Ubiquitous New Kingdom stelae; Allen 2010\n**Date:** formula classical by Middle Egyptian period\n**Confidence:** [attested] consonants; vowels [reconstructed]\n**Notes:** DAVID Post 6 hook."),
("Situate this Middle Egyptian text in its historical and linguistic context.",
 "**Text:** ꜥnḫ wḏꜣ snb\n**Language:** Middle Egyptian | **Date:** c. 2000–1300 BCE classical phase | **Type:** blessing formula\n\n**Source:** Stelae and tomb facades widely\n\n**Context:** Tripartite wish for king or deceased; ꜥnḫ 'live', wḏꜣ 'be whole/prosperous', snb 'be healthy'."),
("How should DAVID handle Middle Egyptian dialect variation in audio production?",
 "**Middle Egyptian — dialect labeling:**\n\nClassical Middle Egyptian for classroom; Late Egyptian shift toward analytic grammar — different stage, tag separately; Coptic is descendant stage — use for vowel reflex model, not identical timbre to ME."),
("What IPA should DAVID use for Middle Egyptian m rn.f n ra?",
 "**Text:** m rn.f n ra\n**IPA:** [mə ˈran.nəf ʔan ˈraʕ]\n**Model:** Allen/Loprieno Coptic-reflex\n**Confidence:** [reconstructed] medium-low vowels; medium-high consonants"),
("What AI lip-sync risks exist for Middle Egyptian video production?",
 "**Middle Egyptian — lip-sync risks:**\n\nPharyngeal ꜥ needs throat constriction viseme AI lacks; ejectives need glottal pop timing; reconstructed vowels make lip-sync look falsely authoritative."),
("How does DAVID translate Middle Egyptian for documentary subtitles?",
 "**Middle Egyptian — translation methodology:**\n\nAllen line gloss convention; grammatical particle labels in overlay; vocalized transliteration separate from consonantal original; tag every vowel insertion [reconstructed]."),
("What Coptic evidence supports Middle Egyptian vowels?",
 "Latest stage of Egyptian with written vowels — reflexes inform Egyptological e/a/i/u insertions; not 1:1 with Middle Egyptian timbre — medium-low confidence."),
("What stress pattern should audio producers use for Middle Egyptian?",
 "Stress placement partly unknown — Allen convention stresses content words; tag [hypothesis]; avoid English stress-timed rhythm."),
("What is Middle Egyptian ꜥ and why do AI models silence it?",
 "Pharyngeal fricative [ʕ] — no English phoneme; TTS drops or vowelizes; reference Arabic ع clips with on-screen phoneme label."),
("How should producers articulate Egyptian ejectives?",
 "pʼ/tʼ/kʼ with audible glottal pop after stop release — Afroasiatic feature rare in European languages; core to authentic reconstruction."),
("What hieroglyphic consonant skeleton hook should tutors use?",
 "Students read snb as s-n-b consonant frame; teacher inserts schwas [səˈnanəjə] — demonstrates script vs speech gap honestly."),
("What emphatic consonants affect Middle Egyptian audio?",
 "q and emphatic series heavier articulation than plain k/t — parallel Semitic emphatics; Peust model guides relative weight."),
("What is the DAVID confidence tag for Middle Egyptian pronunciation?",
 "Revival tier: high for grammar; pronunciation: medium-low vowels, medium-high consonants. Label all vocalized output [reconstructed]."),
("What common subtitle error should Middle Egyptian producers avoid?",
 "Displaying vocalized 'ankh wedja seneb' as attested spelling — original is consonantal ꜥnḫ wḏꜣ snb only; vowels are editorial."),
("How does Middle Egyptian ḫ differ from English th?",
 "ḫ is palatal/velar fricative (like ich-Laut) — not interdental; AI uses English th by false cognate to Greek chi transliteration habit."),
("What corpus is the gold standard for Middle Egyptian classroom pronunciation?",
 "Allen Middle Egyptian textbook worked examples — Sinuhe opening and ꜥnḫ wḏꜣ snb for DAVID canonical samples."),
("What AI training bias causes Middle Egyptian mispronunciation?",
 "Models read transliterated Egyptian like English (Reeves-style) or apply random vowels; also confuse with Arabic without ejective distinction."),
("How should DAVID mark uncertainty in Middle Egyptian revival drafts?",
 "Consonants [attested] from hieroglyphs; vowels mandatory [reconstructed]; stress [hypothesis]; dispute flag per disputed_phonemes.json."),
("What tutoring exercise teaches Middle Egyptian ꜣ glottal?",
 "Contrast ꜣnḫ (glottal onset) with ꜥnḫ (pharyngeal onset) — minimal pair on first consonant only; vowels held constant as schwa placeholders."),
("What Middle Egyptian consonant has no English equivalent?",
 "ꜥ pharyngeal and ejective stops pʼ/tʼ/kʼ — require Arabic/Ge'ez reference sidebar in video."),
("How do determinatives affect pronunciation production?",
 "Determinatives are silent semantic classifiers — strip from phonetic pass; only pronounce spelled consonants and any vowel insertions."),
("What Late Egyptian stage differs for audio pedagogy?",
 "Late Egyptian: analytic syntax shift — not just pronunciation tweak; use separate lesson tag if demonstrating post-Amarna phonology [hypothesis]."),
("What Middle Egyptian vowel epenthesis rule should producers follow?",
 "Egyptological convention inserts ə or a in unstressed open syllables — Allen model; never claim historical certainty."),
("How should translators handle Middle Egyptian suffix pronouns in corpus entries?",
 "Show .f .k .s in transliteration; gloss 'he/you/she' separately; pronounce suffix as consonant + epenthetic vowel [reconstructed]."),
("What is the Middle Egyptian revival tier and what does it imply for production?",
 "Revival tier: high for text grammar; spoken revival is illustrative with persistent vowel disclaimer — suitable for documentary, not drama without subtitles."),
("What near-death pronunciation pitfall affects Middle Egyptian wḏ?",
 "AI reads wḏ as consonant cluster without vowel — insert epenthetic ə for wḏꜣ [ˈwəḏ.ʕaʔ] per Allen vocalization."),
("How does DAVID cross-link Middle Egyptian corpus to History content?",
 "Sinuhe, Akhenaten Amarna texts, Hatshepsut Punt reliefs — tie lesson to period; Amarna as bridge to diplomatic Akkadian corpus."),
("What Middle Egyptian audio reference should Grok Imagine use?",
 "Arabic ع and Ge'ez ejective reference for ꜥ and pʼ/tʼ/kʼ; Allen vocalization demo with visible [reconstructed] watermark."),
("What forensic step precedes Middle Egyptian pronunciation rendering?",
 "Parse hieroglyphic consonants; check Allen vocalization; cross-check Coptic cognate if available; tag vowels before audio synth."),
("What production note applies to Middle Egyptian formulaic phrases?",
 "ꜥnḫ wḏꜣ snb delivered as three balanced beats — documentary audio mirrors tripartite visual composition on tomb walls."),
("What research query should queue after Middle Egyptian vowel lesson?",
 "Sample Greek/Assyrian transcriptions of Egyptian royal names for vowel quality cross-check — research_query_generator.py --language middle-egyptian."),
]
for i, o in ME:
    add(i, o)

assert len(PAIRS) == 200, f"Expected 200 pairs, got {len(PAIRS)}"

out_path = sys.argv[1] if len(sys.argv) > 1 else "david_200_pairs.jsonl"
with open(out_path, "w", encoding="utf-8") as f:
    for p in PAIRS:
        f.write(json.dumps(p, ensure_ascii=False) + "\n")

print(f"Wrote {len(PAIRS)} pairs to {out_path}", file=sys.stderr)